### ISSUE TITLE
Orphan changes in the list

### ISSUE THREAD

**Issue by manulera** [pombase/genome_changelog#20]
This change is listed in the website as change in gene coordinates, but a change was never made. Protein has a length of 551, and the comment says introduces stop codon at position 138.
```
SPCC306.09c	PMID:28631610, PMID:30991417	introduces stop codon at position 138	2020-05-01 00:00:00+00:00									
```

**Comment by manulera** [comment]
cc @ValWood

**Comment by manulera** [comment]
Same for this one:

```
SPAC2F3.04c		truncated 14 AA	2021-11-03 00:00:00+00:00
```

**Comment by ValWood** [comment]
I'm puzzled by 
SPCC306.09c	PMID:28631610, PMID:30991417	introduces stop codon at position 138	2020-05-01 00:00:00+00:00									

because the linked publications are about wtfs. This gene isn't in those papers, and the gene structure looks spot on to me. I think that must have been a mistake.

**Comment by ValWood** [comment]
>SPAC2F3.04c		truncated 14 AA	2021-11-03 00:00:00+00:00

I'm pretty sure the existing gene structure is correct, so not sure what that is about:

>>TR:[S9RIM3](http://www.uniprot.org/uniprot/S9RIM3) S9RIM3_SCHOY Single-stranded DNA binding protein
Rim1 OS=Schizosaccharomyces octosporus (strain yFS286)
OX=483514 GN=SOCG_03073 PE=4 SV=1 (151 aa)
 initn: 423 init1: 405 opt: 451  Z-score: 609.6  bits: 118.9 E(230190370): 8.7e-24
Smith-Waterman score: 451; 48.3% identity (76.8% similar) in 151 aa overlap (2-150:1-151)

               10         20        30        40        50         
SPAC2F MLFLKSSRAFS-KRLFSSSTVRYRDIQRLTLTGNLTKDVERLQSQKGNEYMRYTVASNNG
        .: .: : .  :: :::: .: :::::::.::::..:.::::::.:: ::.::::::::
TR:S9R  MFTHSLRQLCFKRSFSSSPARLRDIQRLTFTGNLARDAERLQSQQGNPYMKYTVASNNG
                10        20        30        40        50         

      60        70        80        90       100        110        
SPAC2F KDVAPTFHSVYVFDSYNFDRLQTILRKGTRVYVEADAVWRSVPAG-NEGSQAKMSLRHVS
       :::  ::..:. ::. .:::..:.:.::..:.:::.:..:. :.  . : .   ::....
TR:S9R KDVPATFRTVFSFDDREFDRMETFLKKGNQVFVEANAIYRNSPSTESAGPSLLSSLQQLN
      60        70        80        90       100       110         

      120       130       140       150 
SPAC2F ADVLFYPRNKNGDESGEETHPELDADPMINSF*
       ...:   :.  ..:   :    ... :. ::: 
TR:S9R VQLLKRARTAVAEEEPAERATPFETGPLPNSF 
     120       130       140       150

**Comment by manulera** [comment]
Ok, I will just close then!
