### ISSUE TITLE
Address svn access for overnight run

### ISSUE THREAD

**Issue by manulera** [pombase/genome_changelog#34]

**Comment by manulera** [comment]
@kimrutherford  sugggested urls in this format that can be set in a parameter file

file:///var/svn-repos/pombe-embl/trunk
svn checkout file:///var/svn-repos/pombe-embl/trunk pombe-embl

**Comment by kimrutherford** [comment]
Hi @manulera

Try this:
```
svn log https://curation.pombase.org/pombe-embl-repo/trunk
```

It should work from anywhere, including on oliver1 itself.

**Comment by manulera** [comment]
It works! 

![](https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWY0NjdlNzQ2ZGFkNzRhZWFjYzUzZDhiNzI2N2Y3YTVhMGE4YTE5OCZjdD1n/tze1mGedykiuk/giphy.gif)
