### ISSUE TITLE
Run as github action?

### ISSUE THREAD

**Issue by manulera** [pombase/genome_changelog#42]
Hi @kimrutherford 

With the new svn repo that I can access without authentication the update of the file can be ran as a github action (the only one in the repo), don't know if that is useful. In principle it should commit the changes but I have to wait for the next change in the repo to test whether it actually does.

**Comment by kimrutherford** [comment]
Hi @manulera

If it's not a lot of work, I think that automating with GitHub Actions is a good idea.

**Comment by manulera** [comment]
It was already done, I am just not sure whether the output will be committed to the repo (I think so but I have to wait until next change in the genome)

**Comment by manulera** [comment]
Hi @kimrutherford the github action works, and made this last commit.

https://github.com/pombase/genome_changelog/commit/0cdc284155e959cb0d1d93687674332ddb966a57

**Comment by manulera** [comment]
Hi @kimrutherford, as you said the action can be easily triggerred using github CLI. I have added a file with the command to do so. It's a one-liner but good to keep it there in case syntax changes.

https://github.com/pombase/genome_changelog/blob/master/trigger_action.sh

I re-open the issue, you can close once this is added to the overnight run.

**Comment by kimrutherford** [comment]
> https://github.com/pombase/genome_changelog/blob/master/trigger_action.sh

Run this weekly, initially.

Investigate running using the pombase GitHub organisation.

**Comment by kimrutherford** [comment]
Hi @manulera

After having a [look at the documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) it looks like we could change the Actions config from:

https://github.com/pombase/genome_changelog/blob/9d5cbdd035ca8096e304cdfc21f469ce356cb650/.github/workflows/update.yml#L2-L5

to:

```yaml
on:
  schedule:
     - cron: '30 2 * * 0,3'
```

Does that seem OK to you?  If so, I'll try it.

"0,3" means Sunday and Wednesday (hopefully).

I wonder if we can allow for the schedule and for the trigger at the same time with something like this?:

```yaml
 on: 
   workflow_dispatch: 
   repository_dispatch: 
     types: [trigger_update]
   schedule:
     - cron: '30 2 * * 0,3'
```

**Comment by manulera** [comment]
> I wonder if we can allow for the schedule and for the trigger at the same time with something like this?:

Hi @kimrutherford. Yes, that looks like it, go ahead. Pretty wild that they are giving all these computing time for free, even allowing users to schedule.

**Comment by manulera** [comment]
> for free

I guess we feed the AI until we make ourselves redundant 🙃

**Comment by kimrutherford** [comment]
> I wonder if we can allow for the schedule and for the trigger at the same time with something like this?:

I struggled to get this to work partly because I wasn't patient enough.  After trying a bunch of possibilities it seems to work now.

**Comment by manulera** [comment]
Hi @kimrutherford. I think I had a similar experience when trying to ping from the CLI to start the action. I did it many times wihtout anything happenning and after a while I had a queue of 10 actions.
