### ISSUE TITLE
Create separate files for RNA and DNA new / deleted genes

### ISSUE THREAD

**Issue by manulera** [pombase/genome_changelog#43]
As dicussed this morning @kimrutherford

**Comment by manulera** [comment]
Hi @kimrutherford the files are there now:

```
results/pombase_tables/
├── gene-coordinate-change-data.tsv
├── new-gene-data-RNA.tsv <
├── new-gene-data-protein-coding.tsv <
├── new-gene-data.tsv
├── removed-gene-data-RNA.tsv <
├── removed-gene-data-protein-coding.tsv <
└── removed-gene-data.tsv
```

* [ ] The `new-gene-data.tsv` and `removed-gene-data.tsv` can be removed once you adapt the code of the website that relies on them.

The `gene-coordinate-change-data.tsv` file does not have to be splitted, right?

**Comment by kimrutherford** [comment]
Thanks Manu!  All done now.
