### ISSUE TITLE
Document how to add manual comments 

### ISSUE THREAD

**Issue by manulera** [pombase/genome_changelog#44]
As discussed this morning @kimrutherford @ValWood add an entry in the wiki of this repo and refer to it from the curation wiki.

**Comment by manulera** [comment]
Hi @ValWood this is done now.

Entry in the curation wiki:
https://github.com/pombase/curation/wiki/Gene-structure-changes,-addition-and-removal

That links to this repo wiki:
https://github.com/pombase/genome_changelog/wiki/Adding-comments-and-references-to-gene-additions,-removals-or-changes

**Comment by ValWood** [comment]
thanks!
