### ISSUE TITLE
Plot of characterisation

### ISSUE THREAD

**Issue by manulera** [pombase/genome_changelog#54]
@kimrutherford @ValWood

Hi, I have changed to similar colours (the ones from the graph are a bit too dim I think, because they are plotted with a strong edge).

I include an example. Also, it is possible to highlight the border, which may be a good idea, let me know if you prefer that.

<img width="300" alt="Screenshot 2023-08-09 at 09 31 05" src="https://github.com/pombase/genome_changelog/assets/22526102/afe24281-253c-4a24-866b-8de2d7d7764d">

<img width="300" alt="Screenshot 2023-08-09 at 09 31 22" src="https://github.com/pombase/genome_changelog/assets/22526102/73bea54f-7add-467c-bf85-c15a32c0ac89">

Also, if you want to plot it as the other graphs in the website so that the colour match is exact, there is a tsv file with the values plotted in the graph here:

https://github.com/pombase/genome_changelog/blob/master/gene_characterisation_status/results/formatted_counts.tsv

**Comment by ValWood** [comment]
The second version without the strong edge is great, but can the colours used for conserved unknown and fission yeast unknown be much paler? This would provide a strong visual separation between known and unknown.

**Comment by manulera** [comment]
What about this one?

https://github.com/pombase/genome_changelog/blob/master/gene_characterisation_status/results/figure.svg

I have moved the colours into a json file, in case you want to change them yourself:

https://github.com/pombase/genome_changelog/blob/master/gene_characterisation_status/color_settings.json

Then you can just run this action and the thing will be re-plotted:

https://github.com/pombase/genome_changelog/actions/workflows/update_characterisation.yml

**Comment by ValWood** [comment]
Ah I see. The colors in the annotation graph are a bit different (the look almost not  'block colour' The green here still seems quite 'strong' but I can see that, if it gets darker it might be difficult to distinguish from the pale yellow. Perhaps a different light colour (lilac?) would work better to keep the contrast and go paler.

Sorry if this seems very trivial to spend time on ;)

**Comment by ValWood** [comment]
ah I see I can change them myself. Will have a go later!

**Comment by ValWood** [comment]
Also we should change the axis from "number of genes" to "number of proteins".

**Comment by manulera** [comment]
This is changed now
