### ISSUE TITLE
Update change log Action failed

### ISSUE THREAD

**Issue by kimrutherford** [pombase/genome_changelog#63]
https://github.com/pombase/genome_changelog/actions/runs/6635033444

Hi @manulera

I think this is a temporary problem with the contig file: https://github.com/pombase/curation/issues/3597#issuecomment-1778166368

I'll check the Action works once the contig is fixed.

**Comment by manulera** [comment]
> I think this is a temporary problem with the co

Ha! I am happy that there was an error message in place 😀

**Comment by kimrutherford** [comment]
Val fixed the contig and the Action now runs without a problem.
